# Generated by Django 5.2.4 on 2025-10-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='reading_type',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='reading_value',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='current',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='vibration',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='voltage',
            field=models.FloatField(null=True),
        ),
    ]
